services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: course_ai_api
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - course_ai_storage:/app/storage

volumes:
  course_ai_storage:
