services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: course_ai_api
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - generated_pdfs:/app/generated_pdfs

volumes:
  generated_pdfs:
